import type { Metadata } from 'next'
import './globals.css'
import Providers from '@/components/Providers'
import localFont from 'next/font/local'

const acuminPro = localFont({
  src: [
    {
      path: '../../public/fonts/Acumin-Pro-Book.otf',
      weight: '400',
    },
    {
      path: '../../public/fonts/Acumin-Pro-Bold.otf',
      weight: '700',
    },
  ],
  variable: '--font-acumin-pro',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${acuminPro.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
